export const theme = {
    red: '#dc3545',
    redOpacity: '#dc3545cc',
    redHover: '#c54119',
    yellow: '#ffff00',
    black: '#000000',
    white: '#ffffff',
    darkgray: '#919191',
    lightgray: '#dee2e6',
    lightergray: '#f5f5f5',
    blue: '#3dbbed',
    blueOpacity: '#3dbbedcc',
    blueHover: '#3197c0',
    blueChecked: '#296085',
    green: '#5bb947',
    shadow: 'box-shadow: 0 0 1rem rgba(0, 0, 0, 0.2)',
    font: {
        size: {
            xxxs: '.8em',
            xxs: '.9em',
            xs: '1em',
            s: '1.2em',
            m: '1.4em',
            l: '2em',
            xl: '4em',
            xxl: '8em',
        },
        weight: {
            light: '300',
            regular: '400',
            bold: '700',
        },
    },
};
